### ISSUE TITLE
Code is not working on Go 1.9

### ISSUE THREAD

**Issue by hexvalid** [jmcfarlane/golang-templates-example#9]
My env: linux/amd64

Problem is:

```
# command-line-arguments
./main.go:23:40: undefined: templateMap

```

**Comment by zelenko** [comment]
Got the same error on  "go1.9.2 windows/amd64".

**Comment by jmcfarlane** [comment]
Interesting, will have a look :)

**Comment by jmcfarlane** [comment]
I don't think there is actually a problem with go.1.9 (or any other version). I think the issue was that you probably ran `go run main.go` which was excluding `functions.go`. In order to not violate the principle of least surprise, I'll move `FuncMap` into `main.go` which should side step this confusion :)
